apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-container-training
spec:
  title: Kubernetes Fundamentals
  description: Workshop on getting started with Kubernetes
  url: https://github.com/paulczar/lab-container-training
  vendor: eduk8s.io
  authors:
    - Paul Czarkowski
    - Jerome Petazzio
  difficulty: intermediate
  duration: 1h
  tags:
    - kubernetes
  content:
    image: paulczar/lab-container-training:master
  # logo:
  session:
    budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
